"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def fib_max(max_val):
  fib_list = [1, 2]
  even_valued_fib_sums = 2
  while (fib_list[-1] + fib_list[-2] < max_val):
    new_num = fib_list[-1] + fib_list[-2]
    fib_list.append(new_num)
    if (new_num % 2 == 0):
      even_valued_fib_sums += new_num
  print(fib_list)
  print(even_valued_fib_sums)
